### PR TITLE
BUG: Fixes Local Schedule Storage Bug

### LINKED ISSUE #20: BUG: Fixes Local Schedule Storage Bug
### Summary
There is a bug found while working on the issue ["FEATURE: More descriptive error message on personal schedule"](https://github.com/ucsb-cs156-w24/proj-courses-w24-5pm-2/issues/5) where the schedule is in local schedule but it's not finding the schedule in the schedules.

### Expected Behavior
localschedule should be found in the schedules

### PR DESCRIPTION
**Pull request by jiaqiguan2003**
In this PR we fixes Local Schedule Storage Bug, so the weird 404 error message cause by local storage doesn't exits anymore

Screen Shot 2024-03-07 at 5 23 27 PM

Screen Shot 2024-03-07 at 5 16 32 PM

Closes #20

### CODE REVIEW

**Review by Maria-Saucedo — APPROVED** [review]
LGTM

**Review by tallyhawley — CHANGES_REQUESTED** [review]
Can you demonstrate that this works?

**Comment by jiaqiguan2003** [comment]
> Can you demonstrate that this works?

the weird 404 error message cause by local storage doesn't exits anymore

Screen Shot 2024-03-07 at 5 23 27 PM

Screen Shot 2024-03-07 at 5 16 32 PM

**Review by Maria-Saucedo — APPROVED** [review]
LGTM

**Review by tallyhawley — APPROVED** [review]
LGTM

**Pull request merged**
