### PR TITLE
REFACTOR: Simplify "Personal schedule" navigation

### LINKED ISSUE #13: REFACTOR: Simplify "Personal schedule" navigation
### Have you updated the title?

- [X] I have updated the issue's title.

### Discussion

If (#65) (Feature Add/remove sections from the personal schedules details page) is done, the navbar for personal schedules can be simplified:
The "add new personal schedule" page link can be moved to the "List all personal schedules" page, and the navbar dropdown can be replaced with just a link to the personal schedules page.
Not needing to go through the dropdown can make navigating through personal schedules more intuitive.

### Acceptance Criteria

- [x] Move the "Add personal schedule" page link from the navbar to a button at the bottom of the "All personal schedules" page.
- [x] In the navbar, instead of a dropdown for "Personal schedules", it simply links to the "all personal schedules" page.

### Implementation Todos

- [x] The above acceptance criteria are done
- [x] Front end tests pass and there is adequate coverage

### PR DESCRIPTION
**Pull request by jiaqiguan2003**
In this PR, we changed the dropdown for Personal schedule nav bar into two links that can just lead you to all personal schedule and all courses. Inside both, you can click on the Add New PS to create ps and/or Add New Course to create courses.

web dev: https://courses-jiaqiguan2003-dev.dokku-06.cs.ucsb.edu

### new nav bar instead of dropdown:
Screen Shot 2024-03-06 at 11 42 30 PM

### click on Personal Schedules will lead to this page and it includes a button to create new PS:
Screen Shot 2024-03-06 at 11 44 02 PM

### click on Courses will lead to this page and it includes a button to create new course:
Screen Shot 2024-03-06 at 11 44 29 PM

Closes #13

### CODE REVIEW

**Review by Maria-Saucedo — DISMISSED** [review]
Everything is functioning as expected, LGTM

**Review by tallyhawley — CHANGES_REQUESTED** [review]
Could you add "Back" buttons on the Personal schedule Details & Edit pages, so that users don't need to use the Navbar to view different schedules?

**Comment by jiaqiguan2003** [comment]
> Could you add "Back" buttons on the Personal schedule Details & Edit pages, so that users don't need to use the Navbar to view different schedules?

implemented back buttons!!!
Screen Shot 2024-03-07 at 6 01 03 PM

Screen Shot 2024-03-07 at 6 00 54 PM

**Review by Maria-Saucedo — APPROVED** [review]
LGTM

**Review by tallyhawley — APPROVED** [review]
LGTM

**Pull request merged**
