### PR TITLE
FEATURE: Add link to developer/GH info in Admin dropdown

### LINKED ISSUE #3: FEATURE: Add link to developer/GH info in Admin dropdown
### Have you updated the title?

- [x] I have updated the issue's title.

### As a...

developer

### I can...

navigate to the GitHub info page

### So that...

I can easily view the GitHub branch info

### Discussion

Currently there is a page at /developer which contains developer info about the GitHub branch, SHA, etc. Please add a link to this page to the Admin dropdown in the navbar.

### Acceptance Criteria

- [x] There is an item in the Admin dropdown called "Developer Info".
- [x] Clicking on this item redirects to [app-link]/developer.

### Implementation Todos

Frontend:
- [x] Add the "Developer Info" item to AppNavbar.js
- [x] Ensure that this item routes to /developer.

Testing:
- [x] Front end tests pass and there is adequate coverage
- [x] Back end tests pass and there is adequate coverage

### PR DESCRIPTION
**Pull request by jiaqiguan2003**
In this PR, we added developer info in admin dropdown in AppNavbar.js and it's test.
http://courses-qa.dokku-06.cs.ucsb.edu
https://courses-qa.dokku-06.cs.ucsb.edu

There is an item in the Admin dropdown called "Developer Info".
Screen Shot 2024-02-27 at 6 19 35 PM

Clicking on this item redirects to [app-link]/developer.
Screen Shot 2024-02-27 at 6 18 28 PM

Closes #3

### CODE REVIEW

**Review by Maria-Saucedo — APPROVED** [review]
LGTM

**Review by tallyhawley — CHANGES_REQUESTED** [review]
Please include a link to your Dokku deployment showing these changes!

**Comment by jiaqiguan2003** [comment]
> Please include a link to your Dokku deployment showing these changes!

http://courses-qa.dokku-06.cs.ucsb.edu
https://courses-qa.dokku-06.cs.ucsb.edu

**Review by AnikaArora — APPROVED** [review]

**Review by tallyhawley — APPROVED** [review]
Looks good to me :shipit:

**Pull request merged**
